### ISSUE TITLE
JsonListModel is not a type

### ISSUE THREAD

**Issue by kjetilge** [Cutehacks/gel#13]
I get JsonListModel is not a type when I try to use this QML type. So the type has obviously not been registered

Aside from following the Cutehacks/Gel install instructions I've also tried:  include(vendor/vendor.pri) in the .pro file and the engine stuff from the qpm manual, but to no avail.

my simple main file: 
```
import QtQuick 2.4
import QtQuick.Window 2.2

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Hello World")

    JsonListModel {

    }
}
```

Any help would be appreciated

**Comment by jrbarron** [comment]
Hi @kjetilge, at least in the example you provided you are missing the import line:

```
import com.cutehacks.gel 1.0
```

That should expose the necessary types to that file.

**Comment by kjetilge** [comment]
Thanks ! It's working now ¯\_(ツ)_/¯
Ironically that import statement is also missing in the sample code in the usage section. Beginners have a hard time guessing what to do. Coming from node/react I really like qt/qml and the concept of qpm. I hope it's possible to to use npm packages soon. That will revolutionize QT/qml :-)

**Comment by jrbarron** [comment]
@kjetilge Great! I'll leave this issue open as a reminder for me to update the docs. Thanks!
