### ISSUE TITLE
README.md: localeCompare should be localeAwareCompare

### ISSUE THREAD

**Issue by marco-piccolino** [Cutehacks/gel#5]

**Comment by jrbarron** [comment]
@marco-piccolino Are you talking about this snippet?

```
function lessThan(a, b) {
    return a.value.localeCompare(b.value) < 0;
}
```

If so, I don't think Javascript has a localeAwareCompare function? Or am I misunderstanding something?

**Comment by marco-piccolino** [comment]
You are right, sorry. I confused it with the  QString method
Il 19/feb/2016 12:51 PM, "Jason Barron" notifications@github.com ha
scritto:
